### PR TITLE
Modified Solution form in order to accept submit function as props.

### LINKED ISSUE #74: SolutionForm is missing prop function to execute when submitting
## Description
Currently the component `SolutionForm` is submitting the solution provided as GET `/currentpath?solution={textareaContent}`, where solution is the name of the text area.

## How

Modify the current component in order to receive a function as props and pass it to the form to be able to submit the form accordingly.

### PR DESCRIPTION
**Pull request by falcoagustin**
Closes #74 

## Impact

Adds function being passed as props to `SolutionForm` component.

### CODE REVIEW

**Comment by nicksp** [comment]
👍

**Comment by nicksp** [comment]
Don't forget to update lib build

**Comment by falcoagustin** [comment]
@nicksp thanks for the catch! Ready for re-review!

**Comment by nicksp** [comment]
Thanks @falcoagustin. Extended examples and merging this now.

**Pull request merged**
