### PR TITLE
Add automated deployment of Github Pages

### LINKED ISSUE #16: Deploy Styleguidist to GH-pages
Deploy Styleguidist bundle to GH-pages.

Suggested approaches:

- https://www.npmjs.com/package/gh-pages-deploy
- https://www.npmjs.com/package/gh-deploy
- https://github.com/x-team/unleash-styles/blob/master/deploy-ghpages.sh (note that on `unleash-styles`, each PR will get a temporary instance on heroku with that branch build of styleguidist, and a "View deployment" link will appear on PR page, in merging details section, this is also nice feature to have)

### PR DESCRIPTION
**Pull request by karolsojko**
closes #16

### CODE REVIEW

**Comment by joshwnj** [comment]
thanks @karolsojko !

**Comment by nicksp** [comment]
Hey @karolsojko As I can see, `auto-ui.x-team.com` doesn't work. How are we supposed to preview deployed page?

**Comment by karolsojko** [comment]
@nicksp https://x-team.github.io/auto-ui/

the custom domain doesn't work yet - working on it

**Comment by nicksp** [comment]
@karolsojko Good to know, thanks for the info 👍 I just wonder why does the build miss some of the styles/assets compared to just a local build https://x-team.github.io/auto-ui/#roadmaptimelineelement

**Comment by karolsojko** [comment]
@nicksp maybe I forgot to run something extra? Have a look in here: https://github.com/x-team/auto-ui/blob/master/.travis.yml#L6-L7

**Comment by nicksp** [comment]
Fixed now.

**Comment by nicksp** [comment]
@joshwnj I'm not sure. Regular Pages page works fine to me :)

**Comment by karolsojko** [comment]
If you guys think there is no need for that then I'll just skip that idea :)

**Pull request merged**
