### PR TITLE
Add size prop to SelectBox component.

### PR DESCRIPTION
**Pull request by rmariuzzo**
**Release Type:** *Non-Breaking Feature*

Fixes https://x-team-internal.atlassian.net/browse/XP-2469

## Description

Add a `size` property to the `SelectBox` component. That new prop is optional and expect one value `'small'` which will make all typography within the `SelectBox` look smaller (16px instead of 20px).

## Checklist

**Before submitting a pull request,** please make sure the following is done:

- [x] set yourself as an assignee
- [x] set appropriate labels for a PR (`In Review` or `In Progress` depending on its status)
- [x] move respective Jira issue to the `IN REVIEW` column
- [x] make sure your code lints (`npm run lint`)
- [x] Flow typechecks passed (`npm run flow`)
- [x] my change requires a change to the component's documentation (`.snap`)
- [x] component's documentation (`.snap`) is changed or added accordingly
- [x] if you've fixed a bug or added code that should be tested, add unit tests
- [x] if any snapshots have been changed, verify that component still works and looks as expected and update the changed snapshot
- [x] **manually tested the component** by running it in the browser and checked nothing is broken and operates as expected!

## Related PRs

branch | PR
------ | ------

## Steps to Test or Reproduce

Go to `SelectBox` in component catalog.

## Impacted Areas in Application

 - `SelectBox`.

### Before:
screen shot 2018-11-22 at 1 38 38 am

### After:
screen shot 2018-11-22 at 1 38 11 am

### CODE REVIEW

**Comment by rmariuzzo** [comment]
@nicksp ty, assigned myself. I want to keep this PR in progress until I create the other PR in auto. Also, I need to double check why the CI failed.

**Comment by rmariuzzo** [comment]
@nicksp just updated the label, I forgot to do that.

**Comment by nicksp** [comment]
Rebased with a Sprint branch to resolve merge conflicts.

**Comment by nicksp** [comment]
Did some more testing with auto integration and noticed that we indeed broke several layout related things:



These bugs relate to what I outlined in a prev review note.

**Comment by nicksp** [comment]
@rmariuzzo Please resolve merge issues. Please note that `Styleguidist` is now gone and a new `Storybook` platform is in use 😄 🎉 Check https://github.com/x-team/auto-ui/pull/264 for details.

**Comment by rmariuzzo** [comment]
@nicksp I fixed those regressions.

**Comment by bernardodiasc** [comment]
@rmariuzzo never mind, found answers in the ticket, good stuff with the new prop approach 👍 

I believe there are more parts missing the upgrade, when testing in all storybook showcases few different inconsistencies appears. For instance take a look at the `"searching" and "creating" use cases` demos.

**Comment by rmariuzzo** [comment]
Thank you @bernardodiasc! I'm gonna take a look again. :)

**Comment by rmariuzzo** [comment]
@bernardodiasc updated PR including the `size` knob in all `SelectBox` component story.

**Pull request merged**
