### PR TITLE
Roadmap Hero Component using Graphic and Copy component

### PR DESCRIPTION
**Pull request by richa**

### CODE REVIEW

**Comment by bernardodiasc** [comment]
Hey @richa :)

This PR looks awesome, I notice that you use the approach I firstly suggested on the issue. But after @joshwnj 's review, some alternatives are raised. I know this is WIP work, just some heads up, can you take a look at these directions:

- We are not going to use the `Graphic` component https://github.com/x-team/auto-ui/issues/13#issuecomment-342994798
- The `Copy` should be renamed to `Text` https://github.com/x-team/auto-ui/issues/12
- The `PageTitle` component will merge with the `Text` component as well https://github.com/x-team/auto-ui/issues/9#issuecomment-342995872 and https://github.com/x-team/auto-ui/issues/26

Cheers!

**Comment by richa** [comment]
Fixes : https://github.com/x-team/auto-ui/issues/9

**Comment by richa** [comment]
roadmaphero

**Comment by joshwnj** [comment]
👍

**Pull request merged**
