### PR TITLE
Resize typography and spacings of components

### PR DESCRIPTION
**Pull request by bernardodiasc**
**Release Type:** *fixes*

Fixes https://x-team-internal.atlassian.net/browse/XP-2364

## Description

Based on a huge discussion regarding the specific approach to apply a zoom out effect in the Lists page, a rough suggestion for new appearance was proposed and this task is about find an harmonic visual that would approach of final design mocks https://d.pr/free/i/dXEkRi

While it's expected a quick-win, this is an S task as reported before, it affects only styles. It was not possible to make the exact changes proposed and get a good and not broken visual as result, so I had to look further, this PR goes in the direction of it's epic https://x-team-internal.atlassian.net/browse/XPM-259:

## Acceptance Criteria

- [x] User must see a tightened up Search Form and search form elements taking up less screen space
- [x] User must see a revised ApplicantBadge that takes up less screen space
- [x] User must see the details from at least 3 applicants in the results when viewing the app at 100% even with a viewport of height 835px

Strategically speaking this PR can be considered a completion of quick fix for the zoom out need:

- **(this PR)** Apply Ryan's CSS Suggestions for element resizing https://x-team-internal.atlassian.net/browse/XP-2364
- **(fine tune on next sprint)** Resize Applicant Badge on List view https://x-team-internal.atlassian.net/browse/XP-2433
- **(fine tune on next sprint)** Resize Search Form elements on List view https://x-team-internal.atlassian.net/browse/XP-2432

/cc @mccrodp

## Checklist

- [x] set yourself as an assignee
- [x] set appropriate labels for a PR (`In Review` or `In Progress` depending on its status)
- [x] move respective Jira issue to the `IN REVIEW` column
- [x] make sure your code lints (`npm run lint`)
- [x] Flow typechecks passed (`npm run flow`)
- [x] my change requires a change to the component's documentation (`.snap`)
- [x] component's documentation (`.snap`) is changed or added accordingly
- [x] if any snapshots have been changed, verify that component still works and looks as expected and update the changed snapshot
- [x] **manually tested the component** by running it in the browser and checked nothing is broken and operates as expected!

## Related PRs

branch | PR
------ | ------
`XP-2364-scale-the-whole-xp-app-down` | [Auto](https://github.com/x-team/auto/pull/1626)

## Screenshots

screen recording 2018-11-02 at 07 30 pm

### 835px view port height 

screen shot 2018-11-02 at 7 45 51 pm

### CODE REVIEW

**Comment by bernardodiasc** [comment]
@nicksp this PR is ready for review again, thanks!

screen shot 2018-11-05 at 4 55 24 pm

screen shot 2018-11-05 at 4 56 02 pm

**Comment by nicksp** [comment]
Resolved merge conflicts

**Comment by mccrodp** [comment]
Nice bug spotting, @nicksp. If a sub-task is needed on a ticket to complete what is already specified, feel free to do that @bernardodiasc, @nicksp! Thanks for your work on this @bernardodiasc!

**Comment by bernardodiasc** [comment]
@nicksp this is ready for review again, thanks!

**Pull request merged**
