### PR TITLE
Use the responsive footer from x-team.com website

### LINKED ISSUE #94: Use the responsive footer from x-team.com
The footer should be applied to the first & last pages of redesigned `auto`.

### PR DESCRIPTION
**Pull request by falcoagustin**
Closes #94 

**Type of release:** _Breaking change._

## Impact

Modifies `Footer` and `FooterList` component in order to remove titles, columns and the X-Icon, showing only the first column of items when resizing the screen (less than 1024px). Also, adds logic to show/hide components when greater than the screen resized before.

## For the reviewer

Go to `Footer` or `FooterList` component and try resizing the screen, the elements with `mobileOnly` set on `true` should appear when screen is smaller than 1024px and disappear when greater, showing only one column of items without logo and titles.

### CODE REVIEW

**Comment by nicksp** [comment]
Committed several improvements to `FooterList` component, mainly to keep the code DRY 😄 

Also noticed the inconsistency between our implementation and x-team.com website's one on `< 1024px`. Compare:

image

image

Should be fixed.

**Comment by nicksp** [comment]
@falcoagustin Is this ready for re-review? I guess so... )

**Comment by falcoagustin** [comment]
@nicksp its ready for re-review 🙂

**Comment by nicksp** [comment]
Alright, after some time of taking care of this, footer seems very close to design and x-team.com website's footer now :-) Had to extensively update all the footer related components. Some of them required altering markup, others changing styles and adding more theme variables in addition to that. Also had to tweak the look of components at different breakpoints to be as responsive as our current `x-team.com` website's footer.

**Pull request merged**
