### PR TITLE
Fix badges with `null` values

### PR DESCRIPTION
**Pull request by RafalWilinski**
Closes: https://github.com/x-team/auto/issues/654

With first name or last name only:
screen shot 2017-11-27 at 9 49 37 am

When both `firstName` and `lastName` is null:
screen shot 2017-11-27 at 9 49 24 am

### CODE REVIEW

**Comment by nicksp** [comment]
Hrm... i thought another developer (me) was already assigned to the ticket. Before starting please check if it's grabbed first. 



Sent from myMail for iOS


Monday, 27 November 2017, 11:55 +0300 from notifications@github.com  <notifications@github.com>:

**Comment by RafalWilinski** [comment]
Sorry @nicksp! 😞  Will do next time!

**Comment by nicksp** [comment]
Yea, please do, it might be the case people might have started the work already



Sent from myMail for iOS


Monday, 27 November 2017, 12:24 +0300 from notifications@github.com  <notifications@github.com>:

**Comment by nicksp** [comment]
Closing in favor of a more complete solution here https://github.com/x-team/auto-ui/pull/56

**Pull request closed without merging**
