### PR TITLE
Add line breaks to note editor

### PR DESCRIPTION
**Pull request by galileo**
**Release Type:** *Bug fix* 

Fixes https://x-team-internal.atlassian.net/browse/XP-2478

## Description

The problem is that in `NewNote` we are using `markdown` as an input and the type for the editor is simple `textarea`. 
In the inline editor we are using the `MediumEditor` and it is expecting the content to be a HTML version. But as we still want to use in there `makrdown` we need only to preserve the line breakings. So that why we changing the `\n` into new line in HTML `<br>`

## Checklist

**Before submitting a pull request,** please make sure the following is done:

- [x] set yourself as an assignee
- [x] set appropriate labels for a PR (`In Review` or `In Progress` depending on its status)
- [x] move respective Jira issue to the `IN REVIEW` column
- [x] make sure your code lints (`npm run lint`)
- [x] Flow typechecks passed (`npm run flow`)
- [x] my change requires a change to the component's documentation (`.snap`)
- [x] component's documentation (`.snap`) is changed or added accordingly
- [x] if you've fixed a bug or added code that should be tested, add unit tests
- [x] if any snapshots have been changed, verify that component still works and looks as expected and update the changed snapshot
- [x] **manually tested the component** by running it in the browser and checked nothing is broken and operates as expected!

## Related PRs

branch | PR

## Impacted Areas in Application

Notes editing
NotesFeeds

## Screenshots
peek 2018-11-22 12-54

### CODE REVIEW

**Comment by nicksp** [comment]
Thanks @galileo I was just wondering why does it work in `sprint-13` without any changes?

**Comment by nicksp** [comment]
@reyronald Since, snapshots have been updated, please give it another check to approve ;-)

**Comment by galileo** [comment]
I published an update into that ticket but regarding the data inconsistency for both editors. We are not able to prepare an input from one source for both of them. We will end up to recieve some glitches until we align the handling method for them. 
Here is the latest behavior for that feature:

peek 2018-11-22 16-02

As you can see when you edit at line ends the content is behaving weirdly.

**Comment by galileo** [comment]
@reyronald @nicksp Can you review it again?

**Pull request merged**
