### PR TITLE
Text Component

### PR DESCRIPTION
**Pull request by richa**
https://github.com/x-team/auto-ui/issues/12

### CODE REVIEW

**Comment by richa** [comment]
screencapture-text-component

**Comment by bernardodiasc** [comment]
@richa I forgot to mention one detail missing, it's also required to include this component module in https://github.com/x-team/auto-ui/blob/master/src/index.js :)

**Comment by nicksp** [comment]
@richa Is this ready for review, as i can see you're still committing things... If so, attach `ready for review` label pls or use `WIP: ` title prefix :)

**Comment by richa** [comment]
@nicksp Sure I'll keep that in mind. Actually the PR was approved and after that I saw conflicts after latest merge. Today, I see another conflict here :)

**Comment by joshwnj** [comment]
thanks @richa .

If the only conflict is `lib/auto-ui.js`, don't worry about it - we can rebuild that file from scratch after merging.

**Comment by joshwnj** [comment]
Looks good, merging now.

**Pull request merged**
