### PR TITLE
Include footer component into pages

### PR DESCRIPTION
**Pull request by bernardodiasc**
https://github.com/x-team/auto/issues/722

### CODE REVIEW

**Comment by nicksp** [comment]
I personally don't feel we need all these changes in a PR. `url` is required prop, and if it's empty will just render non-working `a`. So markup will stay valid and fully operational. So suggest closing without merging unless there're strong arguments

**Comment by bernardodiasc** [comment]
Empty `url` will make links working for same page. This looks like buggy FE to me.

**Comment by bernardodiasc** [comment]
@nicksp I see what you said. We can close this one I guess.

**Comment by bernardodiasc** [comment]
I still prefer to make brand urls optional instead sending empty params and having non-working `<a>`... but let's just move on. :)

**Comment by nicksp** [comment]
@bernardodiasc Good idea, we can get back to it when we feel it's not flexible. For current purposes it works well. Let's keep an eye on it 👍

**Pull request closed without merging**
