### PR TITLE
Tweak footer, fix for situation when more then 4 brands, alignment fix

### PR DESCRIPTION
**Pull request by justtry**
https://github.com/x-team/auto/issues/672

### CODE REVIEW

**Comment by nicksp** [comment]
On mid-size screens to small screens i can see no space between brand images. Compare sketch file:

image

vs current view:

image

In current deployed master specs it looks fine though https://x-team.github.io/auto-ui/#!/FooterBrands

@justtry Also, don't forget to update specs when making PR RFR and run `npm run build` command and commit changes.

image

**Comment by justtry** [comment]
@nicksp thx, run build, margin - added

**Comment by nicksp** [comment]
@justtry Yay, now it looks almost great :) Thanks for the fix. As the last thing before we merge this finally, do you think we can do smth to account for this case on small screens when heading overlaps with the x-logo?

image

**Comment by justtry** [comment]
@nicksp thx, we have a lot of columns and brands, not like on this styleguide, so I think it's not about overlapping but more about having responsive version of site (roadmap and all other elements too)
Thought that responsive is not part of this tickets, but totally can do in terms of this ticket.

**Comment by nicksp** [comment]
@justtry Agree, let's tackle responsive separately once the redesign is completed. Will require applying responsive styles per UI component, by going through all the existing ones. Merging this PR 🎉

**Comment by justtry** [comment]
@nicksp yeah, PR from fork repo

**Pull request merged**
