### PR TITLE
Add item renderer support to Select box component

### PR DESCRIPTION
**Pull request by xvicmanx**
**Release Type:** *Breaking change*

Fixes https://x-team-internal.atlassian.net/browse/XP-2162

## Description

These changes add the following:
 - Add the ability to control the rendering of the items of the SelectBox component.
 - Add the ability to control wether the SelectBox component is bordered or not.

## Checklist

**Before submitting a pull request,** please make sure the following is done:

- [X] set yourself as an assignee
- [X] set appropriate labels for a PR (initially it's mostly `[zube]: In Review`)
- [X] set `[zube]: In Review` label for respective issue as well
- [X] make sure your code lints (`npm run lint`)
- [X] Flow typechecks passed (`npm run typecheck`)
- [X] my change requires a change to the component's documentation (`.snap`)
- [X] component's documentation (`.snap`) is changed or added accordingly
- [X] if any snapshots have been changed, verify that component still works and looks as expected and update changed snapshot
- [X] **manually tested the component** by running it in the browser and checked nothing is broken and operates as expected!

## Related PRs

List related PRs against other Auto repos if applicable:

Branch | PR
------ | ------
XP-2162-add-status-field-component | [Auto](https://github.com/x-team/auto/pull/1538)
XP-2162-add-status-field-component | [Auto API](https://github.com/x-team/auto-api/pull/503)

### CODE REVIEW

**Comment by nicksp** [comment]
Hey @xvicmanx Have you checked that existing uses of `SelectBox` on auto aren't affected by these changes? Have you tested that?

**Comment by xvicmanx** [comment]
Yes, I tested the app.

**Comment by bernardodiasc** [comment]
About items (1) and (2) from my previous comment, it's also expected to have the new item states included in the showcase here http://localhost:6060/#!/SelectBox/11

screenshot-localhost-6060-2018 09 26-20-30-57

And for item (4) will be great to have a new show case with the final API included in the Dropdown showcases, as I demoed in the previous comment.

**Comment by nicksp** [comment]
@bernardodiasc As, @xvicmanx is on another project starting today, could you please take care of this PR?

**Comment by nicksp** [comment]
Hey @bernardodiasc What's the status of the PR? Any progress so far?

**Comment by bernardodiasc** [comment]
hey @nicksp, the items from the list below are covered and ready for review:

> 1. Include radio button styles (can be a prop on SelectBox, and don't really need to be a radio button, just the visual)
> 2. Include the active item state (this part is also required for https://x-team-internal.atlassian.net/browse/XP-2273)
> 3. Change the triangle color (it seems that AddToList also uses wrong color atm)
> 4. Make hasSearch={false} to hide the search (not sure why this is not working as expected atm)

## Included new showcases for SelectBox:
 
screenshot-localhost-6060-2018 10 01-14-33-13

> note, I'm not sure how to render the hasSearch and expanded false with undefined placeholder... the app should not use such API but even that the render should not be just a single line. I left this unresolved to be able to move forward. it's not a blocker.

## Included new showcase for Dropdown:

screen recording 2018-10-01 at 02 41 pm

## Implementation result:

screen recording 2018-10-01 at 02 44 pm

**Comment by nicksp** [comment]
Hey @bernardodiasc Please change that to point to a new sprint branch 😄

**Comment by bernardodiasc** [comment]
@nicksp, I've updated the base branch of the PRs on the 3 repos

**Comment by bernardodiasc** [comment]
I suggested the item:

> 2. Include the active item state (this part is also required for https://x-team-internal.atlassian.net/browse/XP-2273)

as part of this task, but not sure why. Anyway, that was implemented and can be seen in Contact UI already:

screen shot 2018-10-01 at 7 48 32 pm

**Comment by nicksp** [comment]
@bernardodiasc We had a dedicated ticket for that https://x-team-internal.atlassian.net/browse/XPM-195 It's not the best way to mix things together 😛

**Comment by nicksp** [comment]
@bernardodiasc We'll keep it, it's fine, I don't think this is a major issue or smth. Just good to keep in mind when applying changes next time 😄

**Comment by nicksp** [comment]
@bernardodiasc Updated lots of failed snapshots. Expected those to be green though as they were changed in the current PR. Also got a concern: does this use case for `SelectBox` work as expected?

image

I can't see a serahc field here.

**Comment by bernardodiasc** [comment]
> Also got a concern: does this use case for SelectBox work as expected?

That's correct that's wrong. Fixed on this commit https://github.com/x-team/auto-ui/pull/228/commits/5a329861043822d73b8080d47c13df036f23b7d3

With the fix:

screen shot 2018-10-02 at 10 09 35 am

**Comment by bernardodiasc** [comment]
@nicksp about this last update, I double checked, and this version looks "more correct" to me:

screen shot 2018-10-02 at 10 18 58 am

Please let me know which one is expected, if this second one then I send the new commit with the fix.

**Comment by bernardodiasc** [comment]
@nicksp fixed here https://github.com/x-team/auto-ui/pull/228/commits/7e058e2eb19befcd9a4a93c55f85169769ae3261

**Comment by bernardodiasc** [comment]
Oops, forgot to deal with expanded=false case, fixed at https://github.com/x-team/auto-ui/pull/228/commits/ab1f4a433fde1f4619d61d67c0dfe152af3c0ffc

screen shot 2018-10-02 at 10 31 31 am

(without the fix will display the custom placeholder duplicated in the search field)

**Comment by bernardodiasc** [comment]
> Updated lots of failed snapshots. Expected those to be green though as they were changed in the current PR. 

@nicksp regarding this, some components rely on Date API or generate unique IDs in the render, so these will have always red snapshots. `react-select` uses unique IDs, for instance, then `Keywords` and therefore `SearchForm` will be always red. I tried to fix this in Styleguidist but didn't worked well. With a regular Jest setup it's possible to mock these things so snapshots have more stable render output.

But if are referring to other showcases that uses SelectBox/Dropdown and got snapshots updated, then its probably my fault. 😄

**Pull request merged**
