### PR TITLE
Add type attribute to the buttons and check the prop 'isValid'

### PR DESCRIPTION
**Pull request by darieldejesus**
**Release Type:** *New feature* 

Fixes [XP-2237](https://x-team-internal.atlassian.net/browse/XP-2237)

## Description

Add the property `type` to the action buttons and disable the `Save` button if the prop isValid is set to `false`.

## Checklist

**Before submitting a pull request,** please make sure the following is done:

- [x] set yourself as an assignee
- [x] set appropriate labels for a PR (initially it's mostly `[zube]: In Review`)
- [x] set `[zube]: In Review` label for respective issue as well
- [x] make sure your code lints (`npm run lint`)
- [x] Flow typechecks passed (`npm run flow`)
- [x] **manually tested the app** by running it in the browser and checked nothing is broken and operates as expected!

## Related PRs

List related PRs against other Auto repos if applicable:

branch | PR
------ | ------
xp-2237-implement-validators-email-and-location | [Auto](https://github.com/x-team/auto/pull/1534)

## Steps to Test or Reproduce

1. Activate the editor mode of the Location field by clicking the pencil button.
2. Fill it with an invalid location.
3. The `Save` button should be disabled.
3. If you fill it with a valid location, the `Save` button should be enabled.

## Screenshots

screencast 2018-09-21 11-56-58

### CODE REVIEW

**Comment by nicksp** [comment]
Hey, @darieldejesus `npm t` command fails with several Lint and Flow errors. Make sure to check any time you made a commit, please.

**Comment by nicksp** [comment]
Wil l deploy once https://github.com/x-team/auto/pull/1534 is accepted first.

**Comment by darieldejesus** [comment]
@nicksp I ran that command and I didn't see any error. Were you reviewing an outdated version?

**Comment by nicksp** [comment]
@darieldejesus Nope, but I might have rebased with release branch and got some linting errors. No worries, it's fixed now 😏

**Pull request merged**
